name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  publish:
    env:
      EXECUTABLE_PREFIX: ethereum-vanity-wallet
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -v -o ${EXECUTABLE_PREFIX}-${GOOS}-${GOARCH} .

    - name: Rename windows executables
      run: for f in ${EXECUTABLE_PREFIX}-windows-*; do mv "$f" "$f.exe"; done

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE.md
          ${EXECUTABLE_PREFIX}*
