name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  publish:
    env:
      EXECUTABLE_PREFIX: ethereum-vanity-wallet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      env:
        CGO_ENABLED: 0
      run: |
        GOOS=linux GOARCH=amd64     go build -v -o bin/${EXECUTABLE_PREFIX}-linux-x64 .
        GOOS=linux GOARCH=arm       go build -v -o bin/${EXECUTABLE_PREFIX}-linux-arm .
        GOOS=linux GOARCH=arm64     go build -v -o bin/${EXECUTABLE_PREFIX}-linux-arm64 .
        GOOS=windows GOARCH=amd64   go build -v -o bin/${EXECUTABLE_PREFIX}-windows-x64.exe .
        GOOS=windows GOARCH=arm     go build -v -o bin/${EXECUTABLE_PREFIX}-windows-arm.exe .
        GOOS=windows GOARCH=arm64   go build -v -o bin/${EXECUTABLE_PREFIX}-windows-arm64.exe .

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        files: |
          LICENSE.md
          bin/*
